name: econ_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas=2.1.4
  - scipy=1.11.4
  - polars=0.20.21
  - statsmodels=0.14.2
  - matplotlib=3.8.4
  - ipykernel=6.23.0
